// FEATURE BOX STATES
export const DOCUMENT_SCANNER = 'DOCUMENT_SCANNER';
export const SIGN_STAMP = 'SIGN_STAMP';
export const BATCH_SCANNING = 'BATCH_SCANNING';
export const ADVANCED_FILTERS = 'ADVANCED_FILTERS';
export const EXPORT_SHARE = 'EXPORT_SHARE';
